fast_train:
  vectorizer:
    type: HashingVectorizer
    analyzer: char
    ngram_range:
    - 3
    - 5
    n_features: 262144
  model:
    type: LinearSVC
    params:
      max_iter: 2000
      random_state: 42
      class_weight: balanced
      C: 0.25
      loss: squared_hinge
  accuracy:
    test_accuracy: 0.946305
    test_f1: 0.9462620541153411
    cv_mean: 0.9448125000136702
    cv_std: 9.416719484555337e-05
  last_updated: '2025-12-13T12:09:09.613451'
  training_date: '2025-12-13T12:09:09.613463'
